language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    
licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script: 
- ./gradlew build
 
before_install: 
- chmod +x gradlew
- bash .travis-android-license-bugfix.sh

branches: 
only: 
- master
